src/Entity/Property.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */

class Property
{

    const HEAT = [
        0 => "Électrique",
        1 => "Gaz",
        2 => "Géothermique"
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes="image/png"
     * )
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;


    /**
     * @ORM\Column(type="string", length=255)
     * * @Assert\Length(
     *      min = 10,
     *      max = 255,
     *      minMessage = "Le titre doit être composé d'au moins 10 caractères",
     *      maxMessage = "Le titre ne doit pas être composé de plus de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(
     *      min = 10,
     *      max = 400,
     *      minMessage = "La surface doit être supérieur a 10m²",
     *      maxMessage = "La surface doit être inférieur a 400m²")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Regex("/^[0-9]{5}$/")
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Options", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     * @var DateTimeInterface|null
     */
    private $updated_at;

    public function __construct() {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '',' ');
    }
    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType(): string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Options[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Options $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Options $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;
        return $this;
    }

    /* FILE GET & SET */

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Property
     */
    public function setFilename(?string $filename): Property
    {
        $this->filename = $filename;
        return $this;
    }

    /* FILE GET & SET */
    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile = null): Property
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile) {
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Options;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ])
            ->add('options', EntityType::class, [
                'class' => Options::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
        $choices = Property::HEAT;
        $output = [];
        foreach($choices as $k => $v){
            $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php
namespace App\Controller;

use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\PropertySearchType;
use App\Repository\PropertyRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController {

    /**
     * @var PropertyRepository
     */
    private $repository;

    /**
     * @param EntityManagerInterface
     */
    private $em;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/acheter", name="property.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        //Formulaire de rechercher
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);

        //Pagination des biens
        $properties = $paginator->paginate(
            $this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1), 12
        );

        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @return Response
     */
    public function show(Property $property, string $slug) : Response
    {
        if($property->getSlug() !== $slug){
            return $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ], 301);
        }
        return $this->render('property/show.html.twig', [
            'property' => $property,
            'current_menu' => 'properties'
        ]);
    }
}

templates/property/_property.html.twig
{# Base d'affichage des propriétés en carte #}
<div class="card mb-4">
    {% if property.filename %}
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb')}}" alt="image du bien" class="card-img-top">
    {% else %}
        <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb')}}" alt="image du bien" class="card-img-top">
    {%  endif %}
    <div class="card-body">
        <h5 class="card-title">
            {# Récupère l'id pour l'affichage d'une propriété #}
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
                {{ property.title }}
            </a>
        </h5>
        {# Quelques informations sur la propriété #}
        <p class="card-text"> {{ property.surface }}m² - {{ property.rooms }} Pièces</p>
        <p class="card-text"> {{ property.city }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold">
            {{ property.formattedPrice }} €
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Tous nos biens' %}

{% block body %}
    {# Block de la fonction rechercher #}
    <div class="jumbotron">
        <div class="container">
            {{ form_start(form) }}
            <div class="form-row align-items-end">
                <div class="col">
                    {{ form_row(form.minSurface) }}
                </div>
                <div class="col">
                    {{ form_row(form.maxPrice) }}
                </div>
                <div class="col">
                    {{ form_row(form.options) }}
                </div>
                <div class="col">
                    <div class="form-group">
                        <button class="btn btn-primary">Rechercher</button>
                    </div>
                </div>
            </div>
            {{ form_end(form) }}
        </div>
    </div>

    {# Titre de la page #}
    <div class="container mt-4">
        <h1>Retrouvez tous nos biens</h1>

        {# Affichage de toutes les propriétés #}
        <div class="row">
            {% for property in properties %}
                <div class="col-md-4">
                    {%  include 'property/_property.html.twig' %}
                </div>
            {% endfor %}
        </div>

        {# Pagination de la page 'Acheter' #}
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>

{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
    {# Affichage nom - nb de piece - m² - prix - contact (haut droite) #}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    {# Images #}
                    {% if property.filename %}
                        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('medium')}}" alt="image du bien" class="card-img-top">
                    {% else %}
                        <img src="{{ '/images/properties/empty.jpg' | imagine_filter('medium')}}" alt="image du bien" class="card-img-top">
                    {%  endif %}
                </div>
                <div class="col-md-4">
                    <h1>{{ property.title }}</h1>
                    <h2>{{ property.rooms }} Pièces - {{ property.surface }} m² </h2>
                    <div class="text-primary" style="font-size: 3rem; font-weight: bold;">
                        {{ property.formattedPrice }} €
                    </div>
                    <div class="btn btn-primary">
                        Contacter l'agence
                    </div>
                </div>
            </div>
        </div>
    </div>

    {# Description #}
    <div class="container mt-4">
        <p>
            {{ property.description | nl2br }}
        </p>
        {# Affichage caractéristique du bien (bas gauche) #}
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristiques du bien</h2>
                <table class="table table-striped">
                    <tr>
                        <td>Surface habitable</td>
                        <td>{{ property.surface }} m²</td>
                    </tr>
                    <tr>
                        <td>Pièces</td>
                        <td>{{ property.rooms }} </td>
                    </tr>
                    <tr>
                        <td>Chambres</td>
                        <td>{{ property.bedrooms }} </td>
                    </tr>
                    <tr>
                        <td>Étage</td>
                        <td>{{ property.floor }} </td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{ property.heatType }} </td>
                    </tr>
                </table>
            </div>
            {# Affichage spécifité du bien (bas droite) #}
            <div class="col-md-4">
                <h2>Spécifités du bien</h2>
                <ul class="list-group">
                    {% for option in property.options %}
                        <li class="list-group-item">{{ option.name }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}